<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cab.Core\Cab.Core.csproj" />
    <ProjectReference Include="..\Cab.Infrastructure\Cab.Infrastructure.csproj" />
    <ProjectReference Include="..\Cab.Service\Cab.Service.csproj" />
  </ItemGroup>

</Project>
